# Generated by Django 3.2.6 on 2021-08-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_acceptance', models.DateTimeField()),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('courriel', models.EmailField(max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
