# Generated by Django 3.2.6 on 2021-08-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup_ci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeadhesion',
            name='courriel',
            field=models.CharField(max_length=255),
        ),
    ]
