# Generated by Django 3.2.6 on 2021-08-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aup_ci', '0002_auto_20210828_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='fonction',
            new_name='role',
        ),
    ]
