# Generated by Django 3.2.6 on 2021-08-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup_ci', '0002_alter_demandeadhesion_courriel'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadhesion',
            name='traiter',
            field=models.BooleanField(default=False),
        ),
    ]
