# Generated by Django 3.2.6 on 2021-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup_ci', '0003_demandeadhesion_traiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courriel', models.EmailField(max_length=254, unique=True)),
                ('confirme_abonne', models.BooleanField(default=False)),
            ],
        ),
    ]
