# Generated by Django 3.2.6 on 2021-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup_ci', '0004_abonnenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_Mise_a_Jour', models.DateTimeField(auto_now=True)),
                ('sujet', models.CharField(max_length=150)),
                ('contenu', models.FileField(upload_to='uploads/file/newsletters/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image_evenement',
            field=models.ImageField(upload_to='uploads/img/events/'),
        ),
    ]
